version: '3'

services:
  web:
    container_name: votacao-site
    image: votacao-site
    build: .
    restart: always
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`votacao.simplemation.com.br`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.tls=true"
    
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

networks:
  traefik_default:
    external: true